# Default preprocessing preset
# Suitable for all modalities with conservative settings
modality: unknown
description: "Default preset with safe baseline, smoothing, and normalization"
steps:
  - op: baseline
    method: als
    lam: 1.0e5
    p: 0.01
  - op: smoothing
    method: savgol
    window_length: 7
    polyorder: 3
  - op: normalization
    method: snv
